import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
YOUTUBE_TOKEN = os.getenv("YOUTUBE_TOKEN")
DATABASE_URL = os.getenv("DATABASE_URL")
DISCORD_BOTS_TOKEN = os.getenv("DISCORD_BOTS_TOKEN")
DISCORD_BOT_LIST_TOKEN = os.getenv("DISCORD_BOT_LIST_TOKEN")
RBL_BOT_TOKEN = os.getenv("RBL_BOT_TOKEN")
BOT_VERSION = "1.0a"